### ISSUE TITLE
Text of dark colors is illegible

### ISSUE THREAD

**Issue by mb720** [ap/vim-css-color#129]
Hi and thanks a lot for this plugin!

If the color name "black" occurs in a CSS file, I can't read it anymore since it's become a black stripe.

For example, I have this rule in a CSS file:

      kbd
        {
        -moz-border-radius:3px;
        -moz-box-shadow:0 1px 0 rgba(0,0,0,0.2),0 0 0 2px #fff inset;
        -webkit-border-radius:3px;
        -webkit-box-shadow:0 1px 0 rgba(0,0,0,0.2),0 0 0 2px #fff inset;
        background-color:#f7f7f7;
        /* Names of dark colors like black are illegible */
        border:1px solid #ccc;
        border-radius:3px;
        box-shadow:0 1px 0 rgba(0,0,0,0.2),0 0 0 2px #fff inset;
        color:#333;
        display:inline-block;
        line-height:1.4;
        margin:0 .1em;
        padding:.1em .6em;
        text-shadow:0 1px 0 #fff;
      }

On my machine, this looks like something the CIA released ;-)

![CSS rule](https://i.imgur.com/Hy4I5ZX.png)

I'm using Neovim inside Kitty as the terminal emulator.

I have this in my `kitty.conf`:

    foreground #204040
    background #f7f5cd

---

While I was scrolling through the file, the colors suddenly worked:

![CSS rule legible](https://i.imgur.com/xXdHLtJ.png)

This lasted only a briefly. After scrolling to the top of the file and back down to this CSS rule, the color names were illegible again.

Please let me know how to debug this.

---

I tested it with a different terminal emulator, Konsole, seeing the same results.

**Comment by ap** [comment]
The plugin already tries to prevent that from happening. It calculates the brightness of the colour and sets the text colour to black if the colour is light, or white if the colour is dark. That’s what all the variables with “bright” in their name are for.

Does Vim consider your terminal a 256-colour terminal? Because in that case the plugin uses colour 0 for black and colour 15… but of course those indices could be anything. If you’re defining a custom background and foreground colour it could be that the terminal emulator is putting them in those spots in the palette. OTOH, the rectangle on the screenshot is pure `#000000`, no trace of `#204040`, so that doesn’t seem right either. I don’t know what’s going on exactly.

**Comment by mb720** [comment]
> Does Vim consider your terminal a 256-colour terminal?

I'm not sure. `echo $TERM` gives `xterm-kitty`. If I do `export TERM=xterm-256color;` before opening the file, it doesn't seem to have effect.

I just tested with Konsole again and can see that the dark colors are highlighted properly. But when I come to the CSS rule mentioned above, all syntax highlighting is lost, just like with Kitty.

It might be, that I'm observing two unrelated phenomena.

**Comment by ap** [comment]
Why closed…?

**Comment by mb720** [comment]
Because I don't think the issue lies with the plugin, but rather with Kitty. I can reopen if you want.

**Comment by ap** [comment]
Ah. That’s fine then.
