### ISSUE TITLE
Add support for tmux config file

### ISSUE THREAD

**Issue by Fenntasy** [ap/vim-css-color#130]
I assumed it would be possible to use by setting the filetype to `vim` but it does not work everytime.

![image](https://user-images.githubusercontent.com/1764664/81483643-fc32bd00-923f-11ea-9fe9-f226bf68927c.png)

I would love to see this added 🙏 but anyway, thank you for your work 🙇

**Comment by polyzen** [comment]
The tmux syntax file [included with Vim](https://github.com/vim/vim/blob/master/runtime/syntax/tmux.vim) supports highlighting colors:
https://github.com/ericpruitt/tmux.vim/blob/00c795419299fd1497706f52963d4fb44cf63b64/vim/syntax/tmux.vim#L58-L64

I suggest inquiring about extending that support upstream.

**Comment by Fenntasy** [comment]
That's right, 😲 (althought that's foreground color and not background, which could be harder to see). But I don't see why it has no effect in that case.

Thanks for pointing it out.

**Comment by ap** [comment]
@Fenntasy:
> I assumed it would be possible to use by setting the filetype to `vim` but it does not work everytime.

That’s because this plugin doesn’t just turn on or off based on filetype, it actually hooks into each supported syntax and adds highlighting only for pieces of the file where colours are syntactically legal. A Tmux config is not valid VimL code, only bits and pieces of it happen match the patterns expected by the Vim syntax definition, and you get colour highlighting only where the right sub-patterns happen to match.

@polyzen:
> The tmux syntax file [included with Vim](https://github.com/vim/vim/blob/master/runtime/syntax/tmux.vim) supports highlighting colors:

Looks like that is only for terminal colours, not RGB. And it will only work in console Vim.

@Fenntasy:
> althought that's foreground color and not background, which could be harder to see

It does take care to set the background to a contrasting colour, at least. But it does paint the colour onto a lot fewer pixels. There’s a reason this plugin does it the opposite way around. 🙂

**Comment by ap** [comment]
Support added in 533c76425a231afabb8b276b88b055a599e3a1c7. Share and enjoy 🙂
