### ISSUE TITLE
[Question]: Is it possible to disable by default?

### ISSUE THREAD

**Issue by JakeElder** [ap/vim-css-color#136]
Is it possible to have `vim-css-color` disabled by default?

If possible I would rather have it disabled, then toggle it to be enabled/disabled with a key binding IE

```vim
nmap <leader>tcc :call css_color#toggle()
```

**Comment by at1047** [comment]
I couldn't make it work by using startup scripts but if you go into the file in autoload in the plugin there's a function at the bottom called "css_color#init". Inside I commented the line "call css_color#enable()". It still works with a call to css_color#toggle() but disables it on startup.

**Comment by ap** [comment]
Thank you so much for that, @at1047 – I really don’t know why this didn’t occur to myself years ago, it’s so obvious in retrospect. If I hadn’t already made up my mind to [restructure the plugin entirely](/ap/vim-css-color/issues/125#issuecomment-632258909), as mentioned in #125, I’d be implementing your approach right now. And I may still do so anyway when I get around to the restructuring.

I’m closing this particular ticket, since it duplicates #125. (@JakeElder: you may want to subscribe that one.)
