### ISSUE TITLE
Colorcolumn goes on top of the colored css

### ISSUE THREAD

**Issue by davidosomething** [ap/vim-css-color#45]
Makes reading it impossible --
Screenshot: http://screencast.com/t/qqtngvASak

**Comment by ap** [comment]
I don’t think `cursorcolumn` is the problem, but I’d like to test my hypothesis.

Can you redo the screenshot exactly the same except with `:set nocursorcolumn`?

**Comment by davidosomething** [comment]
its `colorcolumn`
cursorcolumn doesn't do anything afaik - returns an error when i do the set command

here it is with `set colorcolumn=0`
http://screencast.com/t/CGT0YBH5sJcD

**Comment by ap** [comment]
Ah. I see now that you wrote `colorcolumn` in the title of this issue, which I didn’t know existed. I misread that as `cursorcolumn` because that most definitely [does something](http://vimdoc.sourceforge.net/htmldoc/options.html#'cursorcolumn'). (Not sure what sort of weird Vim configuration you have that trying to set it gives you an error – your Vim is clearly not compiled without the `+syntax` feature…)

That screenshot doesn’t help – I asked for exactly the same screenshot, only with that setting changed, i.e. the same combination of cursor placement, color value, highlighting, etc. – ideally the same file and cursor position.

**Comment by davidosomething** [comment]
Such a screenshot would look exactly the same -- here it is anyway:
http://screencast.com/t/7nm6uSvG

Here's a video of *cursorcolumn* values on and off with the cursor going to that exact position of that file:
http://screencast.com/t/hQsSomMCmDUN
**colorcolumn** is still on

Here's an image of *cursorcolumn* over the hex color:
http://screencast.com/t/83joJegZe6sx

Here's a video with **colorcolumn** -- the offending setting -- toggled on and off
http://screencast.com/t/DlIs1PxsyGw5

**Comment by ap** [comment]
> Here's an image of `cursorcolumn` over the hex color:
> http://screencast.com/t/83joJegZe6sx

So this one works.

I think I understand the problem, i.e. it’s probably just the same as `cursorline` and `cursorcolumn`, where Vim forcibly combines the overlay highlight with the syntax highlight and gives priority to the overlay. I don’t know if it can be fixed – note how I have support for `cursorline` in the plugin, but not for `cursorcolumn`. That’s for a reason… But I’ll see if I can think of something.

Which colorscheme is that, btw? (I don’t get this problem with my own colorschemes, and I don’t want to have to keep asking you for screenshots…)

**Comment by davidosomething** [comment]
The colorscheme is solarized light
https://github.com/altercation/vim-colors-solarized

```
set background=light
silent! colorscheme solarized
```

**Comment by davidosomething** [comment]
not plugin issue, this is a vim issue
