### ISSUE TITLE
24-bit terminal color support

### ISSUE THREAD

**Issue by ap** [ap/vim-css-color#47]
This requires `has('termtruecolor')` and can then be toggled *at runtime* with `set guicolors`.

Which is a bother, since some of css-color’s optimisations are based on the assumption that it’s necessarily going to be running in *either* a GUI *or* a terminal – but never in an environment than can act like either.

Thanks to @yachi (yachi/vim-css-color@6cb794ce1bbb333de3870efffcc1c37474501ba9).

**Comment by yachi** [comment]
Good to hear that :)
This is from https://github.com/bling/vim-airline/commit/ac58bc995468dced5f0ec2ffdaec2fdc5a465a46
I just look around and see if i can get true css color working, turns out i can't read vim scripts :laughing:.

**Comment by ap** [comment]
@yachi: I believe the most recent version (with Neovim support) will work in a 24-bit capable console vim with no extra patches.

Can you give it a try and yay/nay that?

**Comment by yachi** [comment]
I tried on iTerm nightly (Build 2.9.20160318-nightly
) and neovim and it works! 

![screen shot 2016-03-29 at 11 17 11 am](https://cloud.githubusercontent.com/assets/216480/14097215/7a10509c-f5a1-11e5-9f4c-1f2f23f40024.png)

Great job @ap !

here is the test file https://gist.github.com/yachi/360d85d38513a4831430

but i think there is little issue on vim (with or without truetermcolor patch `choppsv1/term24/vim`):

![screen shot 2016-03-29 at 12 14 27 pm](https://cloud.githubusercontent.com/assets/216480/14097818/0468c6d8-f5a8-11e5-8a05-f7e065ce33e8.png)

I guess it is because my true color in vim is not working
my vim color config
```
if has("nvim")
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
else
  let &t_8f="\e[38;2;%ld;%ld;%ldm"
  let &t_8b="\e[48;2;%ld;%ld;%ldm"
  set guicolors
endif
```

**Comment by ap** [comment]
@yachi: I know NeoVim works and Vim without the truetermcolor cannot work, so I’m only interested in the truetermcolor patch here.

> I guess it is because my true color in vim is not working

Do 24-bit color schemes work with it? Or is it only vim-css-color that is broken?

**Comment by tomxtobin** [comment]
I just pushed in #77 which should cleanly handle 24-bit colors in both Vim 8+ and NeoVim 0.1.5+.

**Comment by ap** [comment]
My remaining question was about the separate terminal truecolor patch that was available separately for Vim 7 and not included in an official release. But even if that patch was not supported, it has been rendered irrelevant by the fact that upstream Vim ships with terminal truecolor support now.

Time to close this issue. Thanks for y’all’s time.
