### ISSUE TITLE
opacity support?

### ISSUE THREAD

**Issue by latel** [ap/vim-css-color#48]
is there a workaround for opacity support?

**Comment by ap** [comment]
Sorry, I don’t know what you mean. Please explain.

**Comment by m-kru** [comment]
@ap I know what @latel meant. Look at the following snippet from poybar config file:
![opacity_polybar](https://user-images.githubusercontent.com/26227737/79037564-9f0d0280-7bd2-11ea-989a-36931994ed80.png)
foreground and background colors have an extra leading byte defining opacity. As you can see vim-css-color does not render color for these colors.

**Comment by zatchheems** [comment]
The "workaround" in this case would be using `rgba` if possible instead of hexadecimal:

![image](https://user-images.githubusercontent.com/8506829/79150401-55691700-7d8e-11ea-9600-e6b59a424ad9.png)

It does still mean that hex colors with that extra byte, like @m-kru said, do not render, and RGBA syntax is not universally available.

**Comment by ap** [comment]
I didn’t realise until only months ago that RGBA hex notation was a thing. And I didn’t get around to implementing support until now, in 96b3942f949cc744f22258057c28cfe394a2cebc.

Sorry it took 5 years for my dumb ass to catch up. 🙂  Share and enjoy!

**Comment by ch3st3r08** [comment]
Hex ARGB values still don't work in Polybar configuration (ft=dosini), did I miss something?
From what I can see, it was only available for CSS
