### ISSUE TITLE
False positives with certain qualifying HTML ids

### ISSUE THREAD

**Issue by dmfay** [ap/vim-css-color#73]
This turned up in a JavaScript file:

<img width="423" alt="screen shot 2016-08-29 at 11 21 20 am" src="https://cloud.githubusercontent.com/assets/3075455/18056711/11a477d8-6ddb-11e6-8a9e-db33a9d7e451.png">

`s:_hexcolor` should look ahead to see if the next character is not whitespace or string/line punctuation (```[`'":;,.\[\]{}()<>]```, possibly others?) which would disqualify a potential color value.

**Comment by ap** [comment]
Yeah, that’s suboptimal. How much does it bother you? I ask because a fix is not that easy.

First of all, making `s:_hexcolor` more restrictive won’t really fix it, because it’s Vim doing the colouring, not the plugin – the plugin just extends the colorscheme dynamically. If it finds `#add` *anywhere* in the file, it will add a `syn match` rule to the colorscheme that will cause this highlight.

So it’s the `syn match` rule (created in the `s:create_syn_match` function) that needs to be more restrictive, not `s:_hexcolor`. In fact, `s:_hexcolor` already finds too much – it’s the integration with the syntax highlighting for each filetype which makes sure that the `syn match` only applies in the right context.

Problem is, the kind of `syn match` created must work in every relevant context in every supported filetype. To make it more restrictive, the same restriction must be valid absolutely everywhere. Maybe that could be done? But there are things like Perl, which allows you to choose almost any string delimiter at all (e.g. you can write `'#add'` as `q-#add-`, where `q` means single-quoted string and the dashes are the delimiters – this can be very handy if you want to write a string that contains other quotes), so you can’t even used a fixed list of characters in the lookahead. OK, so maybe make the `syn match` style filetype-specific. But then there are things like the HTML syntax, which *contains* the CSS and the Javascript syntaxes inside it *within the same buffer*, so the same `syn match` rule must work for *all* of them.

I don’t really have an idea for how to fix your mistaken highlighting. It does not seem possible. Maybe tomorrow or in a year I’ll have a brilliant idea or else a d’uh moment, but for now I can’t help. Sorry…

----

The deeper problem is that Vim’s syntax highlight engine is very, very static. It has no dynamic aspects at all. This plugin manages to make it seem dynamic using on Niklas Hofer’s original idea of just adding more static rules to the colorscheme at runtime. But even though the engine can be pushed pretty far this way, the plugin is ultimately a hack. It has a number of problems and limitations that are ultimately insurmountable without a more dynamic engine.

**Comment by dmfay** [comment]
It's quite tolerable, just a little odd when it happens. Definitely doesn't sound like it's worth rewriting the entire highlight engine over :)

Thanks for the explanation & the plugin!

**Comment by ap** [comment]
Glad you like it. 😊
