### ISSUE TITLE
Whitish colors become blue

### ISSUE THREAD

**Issue by adeele** [ap/vim-css-color#74]
One color interval does not show properly:
![bug](https://cloud.githubusercontent.com/assets/11761582/18250471/f201ec18-7383-11e6-9b4c-8cb7747c6a1b.png)

There are grey-colored: #e5e5e3 and #e5e5f3, but every color between them displays as blue.

**Comment by ap** [comment]
Odd. Is that GUI or console? Either way though, I cannot reproduce this.

Picking `#e5e5f1` as an example, if you type that and then put the cursor on the hex value, what output do you get from this command?

````vim
:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
````

Also, what does `:hi BGe5e5f1` say?

**Comment by adeele** [comment]
I'm using vim in console.
The output is: ['sassCssAttribute', 'BGe5e5f0']
![bug2](https://cloud.githubusercontent.com/assets/11761582/18266252/275e339e-741a-11e6-9bc9-157e6a967303.png)

But after I've read your comment I checked it out and it turned out that my terminal's using its custom color palette to set the background for those colors (still I have no idea why, but seems that's my local issue).
Thanks, great tool by the way!

**Comment by ap** [comment]
Glad you like it. 😊

Yeah, the plugin assumes that `ctermbg=7` will mean `#e5e5e5`, as it does in the usual default VT100 ANSI palette. That may be an unwarranted assumption though. The palette is not standardised and those 16 colours are freely configurable. But the standardised RGB cube is pretty coarse and the 16 other colours could be more accurate for some particular colour so I am reluctant to exclude them… or maybe there should be an option governing whether to use them.

There are even escape sequences in some terminals that allow asking for the actual RGB values of those colours… though apparently only xterm, urxvt and VTE-based terminals (GNOME Terminal etc.) support them.

Then again, maybe you have a recent Vim and a terminal that is compatible with <code>set <a href="http://vimdoc.sourceforge.net/htmldoc/options.html#'tgc'">termguicolors</a></code>**, in which case you can skip the whole deal altogether.

<sub>** That link doesn’t work at the time of this writing because the option was added in Vimdoc site is stuck on Vim 7.3, which is quite out of date.</sub>
