### ISSUE TITLE
[Feature request] Syntax hightlight for Vue

### ISSUE THREAD

**Issue by IniZio** [ap/vim-css-color#84]
Vue is close to JS + HTML combined. Currently I simply copy+paste from the one for js. However it cannot highlight correctly if for the style I use other other languages e.g. Sass,. SCSS

**Comment by ap** [comment]
Can you provide example files? (Like the ones in the `tests/` directory, ideally: one or two examples of each of the relevant syntax features.)

**Comment by IniZio** [comment]
Example Vue file: https://gist.github.com/IniZio/06bfa30c36c1da82c5978f4baa2ed2bf

**Comment by MaThGo** [comment]
Works as expected for me @IniZio:
![bildschirmfoto 2017-03-12 um 10 03 10](https://cloud.githubusercontent.com/assets/463225/23830440/3afc03b6-070b-11e7-8f86-98c9ec3a2024.png)

Colors in the template region are highlighted as well:
![bildschirmfoto 2017-03-12 um 10 04 51](https://cloud.githubusercontent.com/assets/463225/23830446/5fdefab2-070b-11e7-97f3-bd0d6a65148d.png)

Which is not very suprising, since this plugin works by initializing as soon as a compatible syntax coloring is loaded. So if vim detects some css, no matter where as long as vim knows its css, it'll run `after/syntax/css.vim` which will make color highlighting work in css.

Now, take a look at how [posva/vim-vue/syntac](https://github.com/posva/vim-vue/blob/master/syntax/vue.vim) (is there another relevant plugin for this?) is working.

All it does is detecting the regions of the component and tell vim what syntax to use for that region, thus Vim should run `after/syntax/{css,scsss,sass,whatever…}.vim` and enable color highlighting.

Maybe you're using some exotic plugins for vue/sass syntax highlighting?

**Comment by IniZio** [comment]
works as @strflw mentioned after re-installation of my system, might be config problem, closing.
