### ISSUE TITLE
cursorline support sometimes leaves behind spurious highlighting

### ISSUE THREAD

**Issue by alisnic** [ap/vim-css-color#90]
edit: happens after jumping from a css file to a ruby file

<img width="208" alt="screen shot 2017-10-20 at 12 32 21" src="https://user-images.githubusercontent.com/1770351/31814576-c2f72fe4-b592-11e7-8942-f1c8d8c00310.png">

```
$ mvim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  5 2017 04:42:50)
MacOS X (unix) version
Included patches: 1-1175
```

**Comment by ap** [comment]
Weird. What output do you get from the following command if you put the cursor over a mis-highlighted character?

````vim
:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
````

**Comment by alisnic** [comment]
Wow, that's very very wierd. The problem no longer appears. Opened a bunch of ruby files, and cannot reproduce it. If I will ever encouter it again, will post the details. `¯\_(ツ)_/¯`

**Comment by ap** [comment]
Let me guess, you have `cursorline` enabled?

**Comment by alisnic** [comment]
yep

**Comment by ap** [comment]
So the background is that the cursorline overrides syntax highlights beneath it, but `matchadd()` can create match highlights that override the cursorline. Because the plugin is syntax-sensitive, it must use syntax highlights. But it’s also supposed to stay coloured against the cursorline. So it looks at the syntax highlighting of the line under the cursor, and then uses `matchadd()` to create matches that mirror the syntax highlighting for CSS colours. Unfortunately matches are associated with a *window* rather than a buffer, so there have to be triggers to clears the matches when a buffer is no longer shown in a window, and to recreate them when a buffer does get shown in a window. This is where all of this happens: https://github.com/ap/vim-css-color/blob/2411b84298eb6db034001f35ce7cc32c36f9b43b/autoload/css_color.vim#L180-L206 https://github.com/ap/vim-css-color/blob/2411b84298eb6db034001f35ce7cc32c36f9b43b/autoload/css_color.vim#L273-L274

Somehow that fails to work in your case, so a highlight created based on one buffer is left behind when the window switches to showing another buffer.

What is your buffers-and-windows setup?

**Comment by alisnic** [comment]
> Then you switch buffers in that window, and the paint sticks to the window even though the colour name isn’t there any more. Is that right?

Correct. I am an avid user of buffers, I rarely use more than 1 tab, and just always navigate between buffers in the same window (i have `set hidden`)

> What is your buffers-and-windows setup?

[vimrc](https://github.com/alisnic/.dotfiles/blob/macos/.vimrc)
[gvimrc](https://github.com/alisnic/.dotfiles/blob/macos/.gvimrc)

I took a look at your description of your implementation and tried to change `BufWinLeave` and `BufWinEnter` events to `BufLeave` and `BufEnter`, but it didn't help. Will try to hack some more when I will have time in the weekend. Thanks for pointers!

**Comment by ap** [comment]
Well let’s presume nothing and start at zero: are those autocommands actually present? What does `:autocmd CSSColor` say?

**Comment by alisnic** [comment]
```vim
:autocmd CSSColor
--- Auto-Commands ---
CSSColor  BufEnter
    <buffer=1>
              call s:create_matches()
    <buffer=3>
              call s:create_matches()
CSSColor  BufLeave
    <buffer=1>
              call s:clear_matches()
    <buffer=3>
              call s:clear_matches()
CSSColor  ColorScheme
    <buffer=1>
              call css_color#reinit()
    <buffer=3>
              call css_color#reinit()
CSSColor  CursorMoved
    <buffer=1>
              call s:parse_screen()
    <buffer=3>
              call s:parse_screen()
CSSColor  CursorMovedI
    <buffer=1>
              call s:parse_screen()
    <buffer=3>
              call s:parse_screen()
```

**Comment by ap** [comment]
OK, that looks fine…

What does `:echo w:color_match_id` say when you have a correctly painted colour name on the cursor line, and then what does it say after switching buffers and getting the wrong paint?

**Comment by alisnic** [comment]
> echo w:color_match_id

correctly painted: `[24]`
wrong paint: `[]`

**Comment by ap** [comment]
Huh. So `s:clear_matches` did its job but the match sticks around despite that. Very weird.

Does `:call clearmatches()` wipe off the wrong paint?

**Comment by ap** [comment]
Huh. So `s:clear_matches` did its job but the match sticks around despite that. Very weird.

What does `:echo getmatches()` say? Does `:call clearmatches()` wipe off the wrong paint?

**Comment by ap** [comment]
Huh. So `s:clear_matches` did its job but the match sticks around despite that. Very weird.

Can you do that again and then tell what `:echo getmatches()` says as well? Does `:call clearmatches()` wipe off the wrong paint?

**Comment by alisnic** [comment]
correctly painted:

`[{'group': 'BGffffff', 'pattern': '\%1l\%14c....', 'priority': -1, 'id': 5}, {'group': 'BGffffff', 'pattern': '\%1l\%14c....', 'priority': -1, 'id': 47}]'

wrong paing:

`[{'group': 'BGffffff', 'pattern': '\%1l\%14c....', 'priority': -1, 'id': 5}]`

calling `clearmatches()` clears everything up

**Comment by ap** [comment]
Ah, sorry I was unclear. I meant both `:echo w:color_match_id` and `:echo getmatches()`, both times, so I can see if the data structures stay in synch.

Based on what you posted, I have a strong suspicion that we’ll always see more matches listed by `getmatches()` than are recorded in `w:color_match_id`.

**Comment by alisnic** [comment]
inside a css:
<img width="215" alt="screen shot 2017-10-22 at 12 14 11" src="https://user-images.githubusercontent.com/1770351/31860432-a967abf8-b722-11e7-83d1-aed2b558d218.png">

```
echo w:color_match_id
[22]
echo getmatches()
[{'group': 'BGffffff', 'pattern': '\%1l\%14c....', 'priority': -1, 'id': 5}, {'group': 'BGffffff', 'pattern': '\%1l\%14c....', 'priority': -1, 'id': 22}]
```

inside a wrongly-painted file:

<img width="178" alt="screen shot 2017-10-22 at 12 17 57" src="https://user-images.githubusercontent.com/1770351/31860465-1cb6cd82-b723-11e7-9ff0-80664d4e5780.png">

```
echo w:color_match_id
[]
echo getmatches()
[{'group': 'BGffffff', 'pattern': '\%1l\%14c....', 'priority': -1, 'id': 5}]
```

**Comment by ap** [comment]
Right, that confirms my guess. There are two matches, both for the same spot, and `w:color_match_id` only lists one of them.

Unfortunately I don’t have a good guess for how this can happen.

As far as I can tell, by looking at the code of the plugin, there shouldn’t be a way for that to happen. The only places that call `matchadd()` and `matchdelete()` are in the functions I linked in my other comment. The only places that deal with the `w:color_match_id` variable are around them. There does not appear to me to be a way for the code to remove entries from `w:color_match_id` without clearing the corresponding match, so this bug should not be happening.

The only thing I can think of is that something else in your setup is causing the `w:color_match_id` variable to get cleared, so that vim-css-color forgets the matches it has created. Some kind of session management plugin could maybe do that. But I’ve cloned your setup and could not reproduce the bug… so maybe it’s not another plugin to blame?

I’m out of ideas, to be honest.

**Comment by ap** [comment]
Actually, if you move your `~/.vim/` away, reinstall vim-plug and do `:PlugInstall` – can *you* reproduce your own bug?

(I’m grasping at straws here, but this issue seems so bizarre, I don’t want to assume anything.)

**Comment by alisnic** [comment]
Can reproduce with only vim-css-color installed, no other plugins and default colorscheme:

<img width="202" alt="screen shot 2017-10-24 at 09 54 33" src="https://user-images.githubusercontent.com/1770351/31928595-6086669c-b8a1-11e7-820b-36504f180d50.png">

**Comment by ap** [comment]
Good luck!

**Comment by alisnic** [comment]
Hey, I still don't have time to do it, feeling guilty every day about it :( I became a father since then and my free time got reduced drastically. The only thing I was able to confirm that the bug only reproduces if cursorline is enabled and the color is on the first line, so the bug is not that serious.

If anyone else wants to grab this issue, please feel free. I am afraid I won't be able to do this any time soon.

**Comment by ap** [comment]
> I became a father since my last comment here

Congratulations!

> and the color is on the first line

Ah! But first line of what – the file? The window? Or something else?

> I am afraid I won't be able to do this any time soon.

No worries, family comes before some dumb plugin. 😊

**Comment by alisnic** [comment]
> But first line of what – the file?

In my setup it was the first line of the file itself

**Comment by ap** [comment]
I still can’t reproduce it. ☹️

**Comment by alisnic** [comment]
reproduced it in neovim 0.2.1, latest vimrc - https://github.com/alisnic/.dotfiles/blob/macos/.vimrc

![1111](https://user-images.githubusercontent.com/1770351/36962384-07dd165c-2058-11e8-86a7-2ddcc93ef2b3.gif)

**Comment by alisnic** [comment]
2 files that reproduce the problem:

[reproduce.zip](https://github.com/ap/vim-css-color/files/1780799/reproduce.zip)

1. open stylesheet.scss
2. open other.rb

**Comment by ap** [comment]
Got it! Finally. Thank you. As far as I have been able to pinpoint, these are the steps:

1. Make sure `cursorline` is set first
2. Open a file that contains a colour on the first line
3. Switch to another buffer in the same window
4. Result: The colours painted onto the first line of the file opened in step 2 persist on line 1 of the file switched to in step 3

E.g. your repro files are one line each. If I edit each file so that they’re both 4 lines long, and all 4 lines are identical, then go through the steps to reproduce the bug, the result is still a wrong match on the first line only, not the other lines.

Does that match what you are seeing?

**Comment by ap** [comment]
And the answer is that `s:create_matches` always reinitialises `w:color_match_id` with an empty array regardless of whether that variable already exists. So if it gets called several times in a row, with no corresponding `s:clear_matches` call between the calls, then it forgets the matches created during the previous invocation.

And this does happen when opening a file, because it gets called a bunch of times from `s:parse_screen` during the `CursorMoved` event as well as during the `WinBufEnter` and `WinBufLeave` events – and the events do not happen in such a way that a `s:create_matches` call is always preceded by a `s:clear_matches` call.

Mystery solved.

The obvious answer is that `s:create_matches` must clear existing matches before reinitialising the variable.

**Comment by ap** [comment]
> Does that match what you are seeing?

Please let me know if an unaddressed problem remains after this patch.

Otherwise, share and enjoy.

**Comment by alisnic** [comment]
> Please let me know if an unaddressed problem remains after this patch.

Works like a charm! Thank you!
